version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.1.0
  cli: circleci/circleci-cli@volatile

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout

      - orb-tools/validate:
          orb-path: src/orb.yml

  publish:
    executor: cli/default
    steps:
      - checkout

      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: spyscape/rails-orb@dev:$CIRCLE_BRANCH-$CIRCLE_SHA1

workflows:
  version: 2
  validate-publish:
    jobs:
      - validate

      - publish:
          context:
            orb-publishing
          requires:
            - validate
