version: 2.1

description: |
  Build Rails apps

executors:
  default:
    description: Uses the circleci ruby image and the postgres docker image
    parameters:
      ruby-version:
        type: string
      image-options:
        type: string
      postgres-version:
        type: string
      pg-user:
        type: string
      pg-db:
        type: string
      npm-install:
        type: boolean

    docker:
      - image: circleci/ruby:<< parameters.ruby-version >><< parameters.image-options >>
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: localhost
          PGUSER: << parameters.pg-user >>
      - image: postgres:<< parameters.postgres-version >>
        environment:
          POSTGRES_USER: << parameters.pg-user >>
          POSTGRES_DB: << parameters.pg-db >>

commands:
  build-app:
    parameters:
      test-command:
        type: string
      pg-db:
        type: string
      build-assets:
        type: boolean
      npm-install:
        type: boolean
    steps:
      - when:
          condition: << parameters.npm-install >>
          steps:
            - run: npm install

      - run: sudo gem update --system
      - run: gem install bundler

      - restore_cache:
          key: rails-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle --jobs=4 --retry=3

      - save_cache:
          key: rails-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - when:
          condition: << parameters.pg-db >>
          steps:
            - run: bundle exec rake db:setup

      - when:
          condition: << parameters.build-assets >>
          steps:
            - run: bundle exec rake assets:precompile

      - run: << parameters.test-command >>

      - when:
          condition: << parameters.build-assets >>
          steps:
            - run: 
                command: |
                  sudo apt-get update
                  sudo apt-get install openvpn awscli
                  aws s3 cp s3://spyscape-terraform/circleci-spyscape-vpc.ovpn ~/
                  sudo -b openvpn ~/circleci-spyscape-vpc.ovpn
                  sleep 10
            - run: RAILS_ENV=production bundle exec rake assets:precompile
            - persist_to_workspace:
                root: .
                paths:
                  - public

jobs:
  build:
    description: Builds a Rails app
    parameters:
      ruby-version:
        default: "latest"
        description: Ruby version to use
        type: string
      image-options:
        default: ""
        description: Docker image tag options
        type: string
      postgres-version:
        default: "9.6"
        description: Postgres version to use
        type: string
      pg-user:
        type: string
        default: "pguser"
      pg-db:
        type: string
        default: ''
      test-command:
        type: string
        default: bundle exec ./bin/test
      build-assets:
        default: false
        description: whether we want the assets to be built
        type: boolean
      npm-install:
        default: false
        description: Whether we want to install NPM pacakges or not
        type: boolean
    executor:
      name: default
      ruby-version: << parameters.ruby-version >>
      image-options: << parameters.image-options >>
      postgres-version: << parameters.postgres-version >>
      pg-user: << parameters.pg-user >>
      pg-db: << parameters.pg-db >>
      npm-install: << parameters.npm-install >>
    steps:
      - checkout
      - build-app:
          test-command: << parameters.test-command >>
          pg-db: << parameters.pg-db >>
          build-assets: << parameters.build-assets >>
          npm-install: << parameters.npm-install >>
